# Generated by Django 5.1.7 on 2025-03-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillFlowAI', '0002_user_textdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.CharField(default='', max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='textDescription',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
    ]
